# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 18:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ministry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ministry',
            name='members',
            field=models.ManyToManyField(related_name='ministeries', to="accounts.Membership"),
        ),
        migrations.AddField(
            model_name='ministry',
            name='server',
            field=models.ManyToManyField(related_name='ministeries_leading', to="accounts.Membership"),
        ),
    ]
