# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 18:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0002_auto_20171012_1842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ministry',
            old_name='server',
            new_name='leader',
        ),
    ]
