# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 18:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0003_auto_20171012_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ministry',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='ministeries', to=settings.AUTH_USER_MODEL),
        ),
    ]
