# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0004_auto_20171012_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='ministry',
            name='is_baptized',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
