# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0005_ministry_is_baptized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ministry',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='ministeries', to='accounts.Membership'),
        ),
    ]
