# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 14:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0006_auto_20171012_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ministry',
            name='is_baptized',
        ),
    ]
