# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_membership_is_baptized'),
        ('ministry', '0007_remove_ministry_is_baptized'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True)),
                ('contact', models.TextField(blank=True)),
                ('schedule', models.DateTimeField(blank=True, null=True)),
                ('director', models.ManyToManyField(related_name='service_leading', to='accounts.Membership')),
                ('members', models.ManyToManyField(blank=True, related_name='services', to='accounts.Membership')),
            ],
        ),
    ]
