# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 14:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0008_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='schedule',
        ),
    ]
