# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0009_remove_service_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='schedule',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
