# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0010_service_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='schedule',
        ),
        migrations.AddField(
            model_name='service',
            name='day',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
