# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0011_auto_20171015_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='day',
            field=models.CharField(blank=True, choices=[('LU', 'Lunes'), ('MA', 'Martes'), ('MI', 'Miercoles'), ('JU', 'Jueves'), ('VI', 'Viernes'), ('SA', 'Sábado'), ('DO', 'Domingo')], max_length=140, null=True),
        ),
    ]
