# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_membership_address'),
        ('ministry', '0012_auto_20171015_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True)),
                ('contact', models.TextField(blank=True)),
                ('date', models.DateTimeField()),
                ('leader', models.ManyToManyField(related_name='activity_leading', to='accounts.Membership')),
            ],
        ),
        migrations.RenameField(
            model_name='service',
            old_name='director',
            new_name='leader',
        ),
    ]
