# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0013_auto_20171015_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='Dirección')),
                ('email', models.TextField(verbose_name='Correos de contacto')),
                ('phone', models.TextField(verbose_name='Teléfono de contacto')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': 'Actividad', 'verbose_name_plural': 'Actividades'},
        ),
        migrations.AlterModelOptions(
            name='ministry',
            options={'verbose_name': 'Ministerio', 'verbose_name_plural': 'Ministerios'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
        migrations.AlterField(
            model_name='activity',
            name='contact',
            field=models.TextField(blank=True, verbose_name='Datos de contacto'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateTimeField(verbose_name='Fecha de la actividad'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='leader',
            field=models.ManyToManyField(related_name='activity_leading', to='accounts.Membership', verbose_name='Líder'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=140, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='ministry',
            name='contact',
            field=models.TextField(blank=True, verbose_name='Datos de contacto'),
        ),
        migrations.AlterField(
            model_name='ministry',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='ministry',
            name='leader',
            field=models.ManyToManyField(related_name='ministeries_leading', to='accounts.Membership', verbose_name='Líder'),
        ),
        migrations.AlterField(
            model_name='ministry',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='ministeries', to='accounts.Membership', verbose_name='Miembros'),
        ),
        migrations.AlterField(
            model_name='ministry',
            name='name',
            field=models.CharField(max_length=140, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='service',
            name='contact',
            field=models.TextField(blank=True, verbose_name='Datos de contacto'),
        ),
        migrations.AlterField(
            model_name='service',
            name='day',
            field=models.CharField(blank=True, choices=[('LU', 'Lunes'), ('MA', 'Martes'), ('MI', 'Miercoles'), ('JU', 'Jueves'), ('VI', 'Viernes'), ('SA', 'Sábado'), ('DO', 'Domingo')], max_length=140, null=True, verbose_name='Día'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='service',
            name='leader',
            field=models.ManyToManyField(related_name='service_leading', to='accounts.Membership', verbose_name='Líder'),
        ),
        migrations.AlterField(
            model_name='service',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='services', to='accounts.Membership', verbose_name='Miembros'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=140, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='service',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora'),
        ),
    ]
