# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 19:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0014_auto_20171015_1817'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datecontact',
            options={'verbose_name': 'Datos de contacto', 'verbose_name_plural': 'Datos de contacto'},
        ),
    ]
