# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 18:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0016_datecontact_image_map'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datecontact',
            name='image_map',
        ),
    ]
