# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20171012_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='recovery_code',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
