# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('birthday', models.DateTimeField(blank=True, null=True)),
                ('ci', models.IntegerField(null=True)),
                ('phone', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='membership',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='accounts.Membership'),
        ),
    ]
