# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_create_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
