# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20171012_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='ci',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
