# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 18:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20171012_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='membership',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='accounts.Membership'),
        ),
    ]
