# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20171012_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='is_baptized',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
