# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_membership_is_baptized'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='address',
            field=models.TextField(blank=True),
        ),
    ]
