# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_membership_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'verbose_name': 'Miembro', 'verbose_name_plural': 'Miembros'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='membership',
            name='address',
            field=models.TextField(blank=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Cumpleaños'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='ci',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cédula de identidad'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Miembro activo'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='is_baptized',
            field=models.BooleanField(verbose_name='Es bautizado'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='phone',
            field=models.TextField(blank=True, verbose_name='Teléfonos'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='user',
            name='membership',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='accounts.Membership', verbose_name='Membresía'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Teléfono'),
        ),
    ]
