# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 18:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'verbose_name': 'Publicación', 'verbose_name_plural': 'Publicaciones'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=140, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='categories',
            field=models.ManyToManyField(to='blog.Category', verbose_name='Categorías'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='text',
            field=models.TextField(verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(max_length=140, verbose_name='Título'),
        ),
    ]
