# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 23:52
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171015_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='text',
            field=tinymce.models.HTMLField(verbose_name='Contenido'),
        ),
    ]
