# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 00:58
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20171016_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Contenido'),
        ),
    ]
