# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 00:34
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20171016_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='Contenido'),
        ),
    ]
