# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-23 13:00
from __future__ import unicode_literals
from django.db import migrations
from django.utils import timezone
from random import choice


def change_dates_pub(apps, schema_editor):
    # We can't import the model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    pass

class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0010_change_dates_publications'),

    ]

    operations = [
        migrations.RunPython(change_dates_pub),
    ]

